version: '3'

volumes:
  mongodb_data:
  mongodb_config:
  data_gatherer_node_modules:
  rest_backend_pip_modules:

services:

  data_gatherer:
    image: node:8
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    volumes:
      - ./data_gatherer:/data_gatherer
      - data_gatherer_node_modules:/data_gatherer/node_modules
    working_dir: /data_gatherer
    command: npm run start

  rest_backend:
    image: python:3.7
    depends_on:
      - mongo
    environment:
      PYTHONUSERBASE: /rest_backend_pip_modules
      FLASK_ENV: development
      FLASK_APP: /rest_backend
    volumes:
      - ./rest_backend:/rest_backend
      - rest_backend_pip_modules:/rest_backend_pip_modules
    working_dir: /rest_backend
    ports:
      - "50001:5000"
    command: python -m flask run --host=0.0.0.0

  mongo:
    image: mongo:4
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "50017:27017"
    command: mongod
