version: '3'

volumes:
  mongodb_data:
  mongodb_config:

services:

  data_gatherer:
    image: node:8
    depends_on:
      - mongo

  rest_backend:
    image: python:3.7
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    logging:
      driver: "none"
    command: mongod

  server_frontend:
    image: node:8
    depends_on:
      - rest_backend
